### PR TITLE
made changes in request spec files

### PR DESCRIPTION
**Pull request by lena-aiu**

### CODE REVIEW

**Comment by lena-aiu** [comment]
@jrmcgarvey Please check it out. assignments_spec.rb have failures and orders_spec.rb not completed.

**Comment by lena-aiu** [comment]
I think we all need to do after that bin/rails db:migrate RAILS_ENV=test

**Comment by lena-aiu** [comment]
@jrmcgarvey Please check it out. assignments_spec.rb still have failures and orders_spec.rb not completed. Made changes in Views for Videos.

**Review by jrmcgarvey — CHANGES_REQUESTED** [review]
Some changes needed, as we discussed.

1) Many changes needed in assigments_spec.rb as we discussed.
2) Many places where commented out code should be deleted
3) A number of places where the response code 200 is checked, but not the render_template
4) A number of places where response.status is checked for a redirect, but the redirect_to is not checked.

**Comment by lena-aiu** [comment]
@jrmcgarvey Please check changes which I made. Thank you.

**Review by jrmcgarvey — APPROVED** [review]
Looks ok now.  I am merging.

**Pull request merged**
