### PR TITLE
made changes in Navigation and created singe navbar for layout

### PR DESCRIPTION
**Pull request by lena-aiu**

### CODE REVIEW

**Comment by lena-aiu** [comment]
@jrmcgarvey

**Review by jrmcgarvey — CHANGES_REQUESTED** [review]
remove redundant entries in config/routes.rb

**Comment by lena-aiu** [comment]
removed redundant entries in config/routes.rb @jrmcgarvey

**Review by jrmcgarvey — APPROVED** [review]
Ok, looks good, I will merge

**Pull request merged**
